"""Runtime config-block field map for the Utility Tool read tabs.

Originally GENERATED by `_spike/gen_cfg_trif_map.py` from ISM
`FV.IngeBLL.dll` reflection (CfgTrifAU + enums). Labels were re-aligned
to the ISM tool's on-screen names (page-1..page-4 reference screenshots,
2026-05-21) so the operator sees identical terminology in the Utility
Tool and ISM. Parenthetical SI units in ISM labels are dropped — the
`unit` column already renders them, repeating them in the label would
duplicate text in every row.

Live-verified 2026-05-21 against inverters 1/1 (stopped) and 9/2
(running) — value-for-value match with ISM for every field below.

DO NOT edit field/offset/kind/group/enum/bits in place. Those came from
the ISM DLL reflection and changing them silently breaks the decoder.
Label and unit are the safe columns to tweak.
"""
GROUP_TITLES = {
    'A': 'Identity & Clock',
    'B': 'Node & Startup',
    'C': 'Grid Protection Envelope',
    'D': 'Power & Reactive',
    'I': 'Isolation & Temp Derating',
}

FIELDS = [
    # ── A — Identity & Clock ───────────────────────────────────────────
    {'offset': 0,  'field': 'FechaConfiguracion',         'kind': 'dt6',   'enum': None, 'bits': None, 'label': 'Configuration Date - Time',                       'group': 'A', 'unit': '',   'signed': False},
    {'offset': 25, 'field': 'Idioma',                     'kind': 'bits',  'enum': 'eIdiomaLocalOIngles', 'bits': '0', 'label': 'Language',                         'group': 'A', 'unit': '',   'signed': False},
    {'offset': 31, 'field': 'NumGrabaciones',             'kind': 'u16',   'enum': None, 'bits': None, 'label': 'Num Flash rec.',                                  'group': 'A', 'unit': '',   'signed': False},
    {'offset': 32, 'field': 'CountryCode',                'kind': 'u16',   'enum': None, 'bits': None, 'label': 'Country Code',                                    'group': 'A', 'unit': '',   'signed': False},
    {'offset': 80, 'field': 'ValidCfgCode',               'kind': 'u16',   'enum': None, 'bits': None, 'label': 'Cnfg_code',                                       'group': 'A', 'unit': '',   'signed': False},

    # ── B — Node & Startup ─────────────────────────────────────────────
    {'offset': 6,  'field': 'VdcStart',                   'kind': 'u16',   'enum': None, 'bits': None, 'label': 'Starting input voltage',                          'group': 'B', 'unit': 'V',  'signed': False},
    {'offset': 7,  'field': 'TiempoArranqueTension',      'kind': 'u16',   'enum': None, 'bits': None, 'label': 'Starting Vin time',                               'group': 'B', 'unit': 's',  'signed': False},
    {'offset': 8,  'field': 'VdcStop',                    'kind': 'u16',   'enum': None, 'bits': None, 'label': 'Stopping input voltage',                          'group': 'B', 'unit': 'V',  'signed': False},
    {'offset': 16, 'field': 'MarchaParo',                 'kind': 'bits',  'enum': 'EnumMarchaParo',            'bits': '0', 'label': 'Manual Start / Stop',       'group': 'B', 'unit': '',   'signed': False},
    {'offset': 16, 'field': 'ConsignaDeVin',              'kind': 'bits',  'enum': 'eReferenciaTensionEntrada', 'bits': '1', 'label': 'DC Input Voltage Reference','group': 'B', 'unit': '',   'signed': False},
    {'offset': 95, 'field': 'NumeroNodoCAN',              'kind': 'can',   'enum': None, 'bits': None, 'label': 'CAN Bus device number',                           'group': 'B', 'unit': '',   'signed': False},
    {'offset': 96, 'field': 'NumeroNodoModbus',           'kind': 'u16',   'enum': None, 'bits': None, 'label': 'Modbus device number',                            'group': 'B', 'unit': '',   'signed': False},

    # ── C — Grid Protection Envelope ───────────────────────────────────
    {'offset': 10, 'field': 'Vacmin',                     'kind': 'u16',   'enum': None, 'bits': None, 'label': 'Minimum phase voltage',                           'group': 'C', 'unit': 'V',  'signed': False},
    {'offset': 11, 'field': 'Vacmax',                     'kind': 'u16',   'enum': None, 'bits': None, 'label': 'Maximum phase voltage',                           'group': 'C', 'unit': 'V',  'signed': False},
    {'offset': 12, 'field': 'Facmin',                     'kind': 'c100',  'enum': None, 'bits': None, 'label': 'Minimum output frequency',                        'group': 'C', 'unit': 'Hz', 'signed': False},
    {'offset': 13, 'field': 'Facmax',                     'kind': 'c100',  'enum': None, 'bits': None, 'label': 'Maximum output frequency',                        'group': 'C', 'unit': 'Hz', 'signed': False},
    {'offset': 102,'field': 'R40103_Vac_min_num_cycles',  'kind': 'u16',   'enum': None, 'bits': None, 'label': 'Vac_min_num_cycles',                              'group': 'C', 'unit': '',   'signed': False},
    {'offset': 103,'field': 'R40104_Vac_max_num_cycles',  'kind': 'u16',   'enum': None, 'bits': None, 'label': 'Vac_max_num_cycles',                              'group': 'C', 'unit': '',   'signed': False},
    {'offset': 104,'field': 'Freq_min_value_num_cycles',  'kind': 'u16',   'enum': None, 'bits': None, 'label': 'Freq_min_value_num_cycles',                       'group': 'C', 'unit': '',   'signed': False},
    {'offset': 105,'field': 'Freq_max_value_num_cycles',  'kind': 'u16',   'enum': None, 'bits': None, 'label': 'Freq_max_value_num_cycles',                       'group': 'C', 'unit': '',   'signed': False},
    {'offset': 106,'field': 'Vac_min_temp_value',         'kind': 'u16',   'enum': None, 'bits': None, 'label': 'Vac_min_temp_value',                              'group': 'C', 'unit': '',   'signed': False},
    {'offset': 107,'field': 'Vac_max_temp_value',         'kind': 'u16',   'enum': None, 'bits': None, 'label': 'Vac_max_temp_value',                              'group': 'C', 'unit': '',   'signed': False},
    {'offset': 108,'field': 'Freq_min_temp_value',        'kind': 'u16',   'enum': None, 'bits': None, 'label': 'Freq_min_temp_value',                             'group': 'C', 'unit': '',   'signed': False},
    {'offset': 109,'field': 'Freq_max_temp_value',        'kind': 'u16',   'enum': None, 'bits': None, 'label': 'Freq_max_temp_value',                             'group': 'C', 'unit': '',   'signed': False},
    {'offset': 110,'field': 'Vac_min_temp_ticks',         'kind': 'u16',   'enum': None, 'bits': None, 'label': 'Vac_min_temp_ticks',                              'group': 'C', 'unit': '',   'signed': False},
    {'offset': 111,'field': 'Vac_max_temp_ticks',         'kind': 'u16',   'enum': None, 'bits': None, 'label': 'Vac_max_temp_ticks',                              'group': 'C', 'unit': '',   'signed': False},
    {'offset': 112,'field': 'Freq_min_temp_ticks',        'kind': 'u16',   'enum': None, 'bits': None, 'label': 'Freq_min_temp_ticks',                             'group': 'C', 'unit': '',   'signed': False},
    {'offset': 113,'field': 'Freq_max_temp_ticks',        'kind': 'u16',   'enum': None, 'bits': None, 'label': 'Freq_max_temp_ticks',                             'group': 'C', 'unit': '',   'signed': False},
    {'offset': 154,'field': 'VMax_Disc',                  'kind': 'u16',   'enum': None, 'bits': None, 'label': 'VMaxDisconnected',                                'group': 'C', 'unit': 'V',  'signed': False},
    {'offset': 155,'field': 'VMin_Disc',                  'kind': 'u16',   'enum': None, 'bits': None, 'label': 'VMinDisconnected',                                'group': 'C', 'unit': 'V',  'signed': False},
    {'offset': 156,'field': 'FMax_Disc',                  'kind': 'c100',  'enum': None, 'bits': None, 'label': 'FMaxDisconnected',                                'group': 'C', 'unit': 'Hz', 'signed': False},
    {'offset': 157,'field': 'FMin_Disc',                  'kind': 'c100',  'enum': None, 'bits': None, 'label': 'FMinDisconnected',                                'group': 'C', 'unit': 'Hz', 'signed': False},
    {'offset': 158,'field': 'Vgrid_max_slope',            'kind': 'u16',   'enum': None, 'bits': None, 'label': 'Vgrid_max_slope',                                 'group': 'C', 'unit': '',   'signed': False},
    {'offset': 162,'field': 'NominalVoltageInverter',     'kind': 'u16',   'enum': None, 'bits': None, 'label': 'NominalVoltageInverter',                          'group': 'C', 'unit': 'V',  'signed': False},

    # ── D — Power & Reactive ───────────────────────────────────────────
    {'offset': 14, 'field': 'TanFi',                      'kind': 'u16',   'enum': None, 'bits': None, 'label': 'PN tangent',                                      'group': 'D', 'unit': '‰', 'signed': False},  # thousandths (per mille)
    {'offset': 17, 'field': 'PotenciaNominal',            'kind': 'x10',   'enum': None, 'bits': None, 'label': 'Nominal Power',                                   'group': 'D', 'unit': 'W',  'signed': False},
    {'offset': 18, 'field': 'PotenciaLimite',             'kind': 'x10',   'enum': None, 'bits': None, 'label': 'Maximum Power',                                   'group': 'D', 'unit': 'W',  'signed': False},
    {'offset': 90, 'field': 'comp_per_vacio',             'kind': 'u16',   'enum': None, 'bits': None, 'label': 'No load losses compensation',                     'group': 'D', 'unit': '',   'signed': False},
    {'offset': 91, 'field': 'comp_reactiva_x1',           'kind': 'u16',   'enum': None, 'bits': None, 'label': 'Point 1 reactive current digital compensation',   'group': 'D', 'unit': '',   'signed': False},
    {'offset': 92, 'field': 'comp_reactiva_y1',           'kind': 'u16',   'enum': None, 'bits': None, 'label': 'Point 1 reactive power VA compensation',          'group': 'D', 'unit': '',   'signed': False},
    {'offset': 93, 'field': 'comp_reactiva_x2',           'kind': 'u16',   'enum': None, 'bits': None, 'label': 'Point 2 reactive current digital compensation',   'group': 'D', 'unit': '',   'signed': False},
    {'offset': 94, 'field': 'comp_reactiva_y2',           'kind': 'u16',   'enum': None, 'bits': None, 'label': 'Point 2 reactive power VA compensation',          'group': 'D', 'unit': '',   'signed': False},

    # ── I — Isolation & Temp Derating ──────────────────────────────────
    {'offset': 22, 'field': 'KZdc',                       'kind': 'x10',   'enum': None, 'bits': None, 'label': 'Isolation Impedance Zdc',                         'group': 'I', 'unit': 'Ω', 'signed': False},  # Ω (ohm)
    {'offset': 33, 'field': 'DifFalloAisl',               'kind': 'recta', 'enum': None, 'bits': None, 'label': 'Max admissible imbalance of panels-to-ground voltage', 'group': 'I', 'unit': '%Vpv', 'signed': False},
    {'offset': 115,'field': 'ExpectedIDC',                'kind': 'u16',   'enum': None, 'bits': None, 'label': 'Expected IDC',                                    'group': 'I', 'unit': 'A',  'signed': False},
    {'offset': 159,'field': 'CX_Waiting_Time_PI',         'kind': 'u16',   'enum': None, 'bits': None, 'label': 'CX_Waiting_Time_PI',                              'group': 'I', 'unit': '',   'signed': False},
    {'offset': 160,'field': 'Waiting_time_COM',           'kind': 'u16',   'enum': None, 'bits': None, 'label': 'Waiting_time_COM',                                'group': 'I', 'unit': '',   'signed': False},
    {'offset': 161,'field': 'EOF_timeout',                'kind': 'u16',   'enum': None, 'bits': None, 'label': 'EOF_timeout',                                     'group': 'I', 'unit': '',   'signed': False},
    {'offset': 168,'field': 'MaxVocValue',                'kind': 'u16',   'enum': None, 'bits': None, 'label': 'Max. Vdc Value',                                  'group': 'I', 'unit': 'V',  'signed': False},
    {'offset': 169,'field': 'AmbTempRedRate',             'kind': 'u16',   'enum': None, 'bits': None, 'label': 'Ambient Temperature Reduction Power',             'group': 'I', 'unit': '%Pn','signed': False},
    {'offset': 170,'field': 'AmbTempRedTemp',             'kind': 'u16',   'enum': None, 'bits': None, 'label': 'Ambient Temperature Reduction Temperature',       'group': 'I', 'unit': '°C', 'signed': False},  # °C
    {'offset': 171,'field': 'InomWithTempDerating',       'kind': 'u16',   'enum': None, 'bits': None, 'label': 'Inverter nominal current with maximum temperature derating @ 80°C', 'group': 'I', 'unit': 'A', 'signed': False},
    {'offset': 172,'field': 'IMAXWithoutTempDerating',    'kind': 'u16',   'enum': None, 'bits': None, 'label': 'Inverter maximum current without temperature derating', 'group': 'I', 'unit': 'A', 'signed': False},
]

ENUMS = {
}
