# Generates a self-signed code signing certificate for the ADSI Inverter Dashboard.
# Run this once. The PFX is stored in build/private/ (gitignored).
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File scripts/generate-codesign-cert.ps1
#
# Output:
#   build/private/codesign.pfx       - PRIVATE KEY (keep secret, back up to password manager)
#   build/private/codesign.cer       - PUBLIC CERT (install on gateway machine)
#   build/private/codesign.env       - PRIVATE env vars for electron-builder
#   build/private/codesign-thumbprint.txt - cert thumbprint reference
#
# Notes:
#   - 4096-bit RSA, SHA-256, 10-year validity
#   - Includes Code Signing EKU (1.3.6.1.5.5.7.3.3)
#   - Subject uses UTF-8 encoding for the n-tilde character

$ErrorActionPreference = "Stop"

# Resolve paths relative to repo root (this script lives in scripts/)
$RepoRoot = Split-Path -Parent $PSScriptRoot
$PrivateDir = Join-Path $RepoRoot "build\private"

if (-not (Test-Path $PrivateDir)) {
    New-Item -ItemType Directory -Path $PrivateDir -Force | Out-Null
}

$PfxPath = Join-Path $PrivateDir "codesign.pfx"
$CerPath = Join-Path $PrivateDir "codesign.cer"
$EnvPath = Join-Path $PrivateDir "codesign.env"
$ThumbPath = Join-Path $PrivateDir "codesign-thumbprint.txt"

if (Test-Path $PfxPath) {
    Write-Host "[!] $PfxPath already exists." -ForegroundColor Yellow
    Write-Host "    Refusing to overwrite. Delete it manually if you want to regenerate." -ForegroundColor Yellow
    Write-Host "    Regenerating will break auto-update for any already-installed dashboard." -ForegroundColor Yellow
    exit 1
}

Write-Host "[*] Generating self-signed code signing certificate..." -ForegroundColor Cyan

# Subject distinguished name
# Using UTF-8 form for the n-tilde character via PowerShell -Subject parameter
$Subject = [string]([char]0x0022 + "CN=Engr. Clariden D. Monta" + [char]0x00F1 + "o REE, O=MCTech Engineering, C=PH" + [char]0x0022)
# Strip the surrounding quotes added above (used to keep the literal intact in source)
$Subject = $Subject.Trim('"')

$cert = New-SelfSignedCertificate `
    -Subject $Subject `
    -Type CodeSigningCert `
    -KeyAlgorithm RSA `
    -KeyLength 4096 `
    -HashAlgorithm SHA256 `
    -KeyUsage DigitalSignature `
    -KeyExportPolicy Exportable `
    -CertStoreLocation "Cert:\CurrentUser\My" `
    -NotAfter (Get-Date).AddYears(10) `
    -FriendlyName "ADSI Inverter Dashboard Code Signing" `
    -TextExtension @(
        "2.5.29.37={text}1.3.6.1.5.5.7.3.3",
        "2.5.29.19={text}CA=false"
    )

if (-not $cert) {
    Write-Host "[!] Certificate generation failed." -ForegroundColor Red
    exit 1
}

$thumbprint = $cert.Thumbprint
Write-Host "[+] Certificate created. Thumbprint: $thumbprint" -ForegroundColor Green

# Generate a strong random password for the PFX
Add-Type -AssemblyName System.Web
$plainPassword = [System.Web.Security.Membership]::GeneratePassword(32, 6)
$securePassword = ConvertTo-SecureString -String $plainPassword -Force -AsPlainText

# Export PFX (private key + cert)
Write-Host "[*] Exporting PFX (private key) to $PfxPath" -ForegroundColor Cyan
Export-PfxCertificate -Cert $cert -FilePath $PfxPath -Password $securePassword | Out-Null

# Harden NTFS ACLs on the PFX so only the current user can read it.
# Disables inheritance and removes all access except the current user.
Write-Host "[*] Hardening NTFS ACL on PFX (current user only)" -ForegroundColor Cyan
try {
    $currentUser = [System.Security.Principal.WindowsIdentity]::GetCurrent().User
    $acl = Get-Acl $PfxPath
    $acl.SetAccessRuleProtection($true, $false)  # Disable inheritance, do not preserve inherited rules
    # Strip every existing ACE
    $acl.Access | ForEach-Object { [void]$acl.RemoveAccessRule($_) }
    # Add full control for the current user only
    $rule = New-Object System.Security.AccessControl.FileSystemAccessRule(
        $currentUser,
        [System.Security.AccessControl.FileSystemRights]::FullControl,
        [System.Security.AccessControl.InheritanceFlags]::None,
        [System.Security.AccessControl.PropagationFlags]::None,
        [System.Security.AccessControl.AccessControlType]::Allow
    )
    $acl.AddAccessRule($rule)
    Set-Acl -Path $PfxPath -AclObject $acl
    Write-Host "[+] PFX ACL hardened" -ForegroundColor Green
} catch {
    Write-Host "[!] Failed to harden PFX ACL: $_" -ForegroundColor Yellow
    Write-Host "    File is still gitignored but is readable by other users on this machine." -ForegroundColor Yellow
}

# Export CER (public cert only - for distribution to gateway machine)
Write-Host "[*] Exporting CER (public cert) to $CerPath" -ForegroundColor Cyan
Export-Certificate -Cert $cert -FilePath $CerPath -Type CERT | Out-Null

# Write env file for electron-builder
$envContent = @"
# Generated by scripts/generate-codesign-cert.ps1
# DO NOT COMMIT - gitignored via build/private/
CSC_LINK=build/private/codesign.pfx
CSC_KEY_PASSWORD=$plainPassword
"@
[System.IO.File]::WriteAllText($EnvPath, $envContent, [System.Text.UTF8Encoding]::new($false))

# Write thumbprint reference
[System.IO.File]::WriteAllText($ThumbPath, $thumbprint, [System.Text.UTF8Encoding]::new($false))

# Remove the cert from CurrentUser\My store so it doesn't pollute the personal cert store
Write-Host "[*] Removing cert from CurrentUser\My store (PFX is the canonical copy)" -ForegroundColor Cyan
Remove-Item -Path "Cert:\CurrentUser\My\$thumbprint" -Force

Write-Host ""
Write-Host "================================================================" -ForegroundColor Green
Write-Host "  CERTIFICATE GENERATED SUCCESSFULLY" -ForegroundColor Green
Write-Host "================================================================" -ForegroundColor Green
Write-Host ""
Write-Host "  Subject:    $Subject"
Write-Host "  Thumbprint: $thumbprint"
Write-Host "  Validity:   10 years"
Write-Host "  Algorithm:  RSA-4096 / SHA-256"
Write-Host ""
Write-Host "  Files written:"
Write-Host "    $PfxPath  [PRIVATE - back this up!]"
Write-Host "    $CerPath  [PUBLIC - install on gateway machine]"
Write-Host "    $EnvPath  [PRIVATE - env vars for build]"
Write-Host ""
Write-Host "  NEXT STEPS:" -ForegroundColor Yellow
Write-Host "  1. Back up build/private/codesign.pfx and codesign.env to a safe place"
Write-Host "  2. Run: npm run build:installer:signed"
Write-Host "  3. On the gateway machine, install build/private/codesign.cer"
Write-Host "     Right-click .cer  ->  Install Certificate  ->  Local Machine  ->"
Write-Host "     'Place all certificates in the following store'  ->  Browse  ->"
Write-Host "     'Trusted Root Certification Authorities'  ->  OK"
Write-Host ""
